name: Deploy to production environment
on:
  push:
    branches:
      - main

jobs:
  deploy-action-prod:
    name: deploy-action-prod
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          host: ${{ secrets.PROD_SSH_HOSTNAME }}
          username: ${{ secrets.PROD_SSH_USER }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            cd ${{ secrets.PROD_DEPLOY_DIR }}
            ls
